---
debug: true
contextTimeout: 5

server:
  port: "80"
  host: "0.0.0.0"
  env: "local"
  useRedis: false

services:

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "payment-service"
