---
debug: true
contextTimeout: 5

server:
  port: "8082"
  host: "127.0.0.1"
  env: "local"
  useRedis: false

services:

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "item-service"
