---
debug: true
contextTimeout: 5

server:
  port: "80"
  host: "0.0.0.0"
  env: "local"
  useRedis: false
  myURL: "http://order-service/api/order"

services:
  itemServiceURL: "http://item-service/api/item"
  paymentServiceURL: "http://payment-service/api/payment"
  dtmServiceURL: "http://dtm-service:36789/api/dtmsvr"

database:
  driver: "postgres"
  host: "db"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "order_service"
